name: misix
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.1

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^5.2.1
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/audio/
    - assets/audio/tanpa_cinta.mp3
    - assets/audio/Pesan_Terakhir.mp3
    - assets/audio/Bawa_Dia_Kembali.mp3
    - assets/audio/Confident.mp3
    - assets/audio/Flatline.mp3
    - assets/avatars/
    - assets/covers/